service: BSU-Hackathon2022-API

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2

functions:
  app:
    handler: index.handler
    events:
      - http: GET /api/v1/products/{barcode}
      - http: POST /api/v1/products
