AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: myFirstFunction

Globals:
  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 100

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers
      Handler: parser.parserHandler
      MemorySize: 512