service: BSU-Hackathon2022-FOOD-TRACKER-API

provider:
  name: aws
  runtime: nodejs14.x
  stage: stage
  region: us-east-2

functions:
  app:
    handler: src/handlers/server.handler
    events:
      - http: GET /products
      - http: POST /products
